const products = [
  {
    id: 1,
    name: "Assam Street-Style Masala Chai",
    subtitle: "Bold & spicy authentic street chai blend",
    slug: "assam-masala-chai",
    category: "Trial Pack",
    type: ["Black", "Masala"],
    flush: "Summer",
    region: "Assam",
    packaging: "Whole Leaf",
    quantity: "2 Boxes (100g each)",
    price: 499,
    originalPrice: 599,
    offer: "Buy 10 Get 10 Free",
    giftIncluded: true,
    rating: 4.9,
    reviewCount: 173,
    badges: ["New", "Bestseller", "Gift"],
    origin: "Doomni Estate, 1800 ft elevation",
    harvestDate: "April 2025",
    brewing: { temperature: "100°C", time: "5 min simmer with milk" },
    tasteNotes: ["Spicy", "Bold", "Warming"],
    tags: ["masala", "ctc", "chai lover", "trial pack"],
    image: "/uploads/Assam_Street-Style_Masala_Chai.png",
    images: ["/uploads/Assam_Street-Style_Masala_Chai.png"]
  },
  {
    id: 2,
    name: "Darjeeling Earl Grey – Autumn Flush",
    subtitle: "Premium bergamot-infused Darjeeling classic",
    slug: "darjeeling-earl-grey",
    category: "Full-Sized",
    type: ["Black"],
    flush: "Autumn",
    region: "Darjeeling",
    packaging: "Whole Leaf",
    quantity: "1 Tin (100g)",
    price: 699,
    originalPrice: 799,
    offer: "10% Off + Free Steel Tea Scoop",
    giftIncluded: true,
    rating: 4.7,
    reviewCount: 92,
    badges: ["Organic", "Gift"],
    origin: "Makaibari Estate, 4500 ft",
    harvestDate: "Nov 2024",
    brewing: { temperature: "90°C", time: "3 mins" },
    tasteNotes: ["Citrusy", "Floral", "Light-bodied"],
    tags: ["earl grey", "autumn", "bergamot", "gift tin"],
    image: "/uploads/Darjeeling_Earl_Grey_Autumn_Flush.png",
    images: ["/uploads/Darjeeling_Earl_Grey_Autumn_Flush.png"]
  },
  {
    id: 3,
    name: "Assam Masala Tea",
    subtitle: "Traditional Assamese masala blend",
    slug: "assam-masala-tea",
    category: "Trial Pack",
    type: ["Black", "Masala"],
    flush: "Summer",
    region: "Assam",
    packaging: "Loose Leaf",
    quantity: "100g (Loose Leaf)",
    price: 399,
    originalPrice: 449,
    offer: "Free Sample Pack with Order",
    giftIncluded: false,
    rating: 4.8,
    reviewCount: 156,
    badges: ["Popular", "Traditional"],
    origin: "Assam Valley, 500 ft elevation",
    harvestDate: "June 2025",
    brewing: { temperature: "100°C", time: "4-5 mins with milk" },
    tasteNotes: ["Rich", "Malty", "Strong"],
    tags: ["assam", "masala", "traditional", "milk tea"],
    image: "/uploads/Assam_Masala_Tea.png",
    images: ["/uploads/Assam_Masala_Tea.png"]
  },
  {
    id: 4,
    name: "Punjabi Masala Tea",
    subtitle: "Rich cardamom & ginger spiced blend",
    slug: "punjabi-masala-tea",
    category: "Trial Pack",
    type: ["Black", "Masala"],
    flush: "Summer",
    region: "Punjab",
    packaging: "Loose Leaf",
    quantity: "100g",
    price: 449,
    originalPrice: 529,
    offer: "Buy 2 Get 20% Off",
    giftIncluded: false,
    rating: 4.7,
    reviewCount: 89,
    badges: ["Regional", "Spiced"],
    origin: "Punjab Plains, 300 ft elevation",
    harvestDate: "May 2025",
    brewing: { temperature: "100°C", time: "6-8 mins boiled with milk" },
    tasteNotes: ["Cardamom", "Ginger", "Robust"],
    tags: ["punjabi", "masala", "cardamom", "authentic"],
    image: "/uploads/Punjabi_Masala_Tea.png",
    images: ["/uploads/Punjabi_Masala_Tea.png"]
  },
  {
    id: 5,
    name: "Kolkata Street Tea",
    subtitle: "Authentic Bengali street style brew",
    slug: "kolkata-street-tea",
    category: "Trial Pack",
    type: ["Black"],
    flush: "Summer",
    region: "West Bengal",
    packaging: "Loose Leaf",
    quantity: "100g",
    price: 349,
    originalPrice: 399,
    offer: "Free Delivery on First Order",
    giftIncluded: false,
    rating: 4.6,
    reviewCount: 134,
    badges: ["Street Style", "Cultural"],
    origin: "Bengal Tea Gardens, 200 ft elevation",
    harvestDate: "April 2025",
    brewing: { temperature: "100°C", time: "3-4 mins strong brew" },
    tasteNotes: ["Bold", "Malty", "Sweet"],
    tags: ["kolkata", "street", "bengal", "cultural"],
    image: "/uploads/Kolkata_Street_Tea.png",
    images: ["/uploads/Kolkata_Street_Tea.png"]
  },
  {
    id: 6,
    name: "Bombay Cutting Tea",
    subtitle: "Quick & strong Mumbai-style chai",
    slug: "bombay-cutting-tea",
    category: "Trial Pack",
    type: ["Black"],
    flush: "Summer",
    region: "Maharashtra",
    packaging: "Loose Leaf",
    quantity: "100g",
    price: 379,
    originalPrice: 429,
    offer: "Mumbai Special: Free Shipping",
    giftIncluded: false,
    rating: 4.5,
    reviewCount: 98,
    badges: ["Mumbai Style", "Popular"],
    origin: "Western Ghats, 800 ft elevation",
    harvestDate: "May 2025",
    brewing: { temperature: "100°C", time: "2-3 mins cutting style" },
    tasteNotes: ["Strong", "Quick", "Energizing"],
    tags: ["bombay", "cutting", "mumbai", "quick"],
    image: "/uploads/Bombay_Cutting_Tea.png",
    images: ["/uploads/Bombay_Cutting_Tea.png"]
  },
  {
    id: 7,
    name: "Kashmiri Kahwa Saffron (Kesar) Green",
    subtitle: "Luxurious saffron & almond green tea",
    slug: "kashmiri-kahwa-saffron",
    category: "Trial Pack",
    type: ["Green", "Herbal"],
    flush: "Spring",
    region: "Kashmir",
    packaging: "Teabags",
    quantity: "15 Teabags",
    price: 599,
    originalPrice: 699,
    offer: "Premium Saffron: Free Honey Sachet",
    giftIncluded: true,
    rating: 4.9,
    reviewCount: 78,
    badges: ["Premium", "Saffron", "Wellness"],
    origin: "Kashmir Valley, 5000 ft elevation",
    harvestDate: "March 2025",
    brewing: { temperature: "85°C", time: "5-6 mins for full flavor" },
    tasteNotes: ["Saffron", "Almond", "Aromatic"],
    tags: ["kashmir", "kahwa", "saffron", "premium"],
    image: "/uploads/Kashmiri_Kahwa_Saffron_(Kesar)_Green.png",
    images: ["/uploads/Kashmiri_Kahwa_Saffron_(Kesar)_Green.png"]
  },
  {
    id: 8,
    name: "Green Tea Rose Glow",
    subtitle: "Beauty blend with organic rose petals",
    slug: "green-tea-rose-glow",
    category: "Full-Sized",
    type: ["Green"],
    flush: "Summer",
    region: "Kangra",
    packaging: "Tin",
    quantity: "75g Tin",
    price: 549,
    originalPrice: 649,
    offer: "Beauty Pack: Free Rose Petals",
    giftIncluded: false,
    rating: 4.8,
    reviewCount: 145,
    badges: ["Beauty", "Organic", "Bestseller"],
    origin: "Kangra Valley, 2500 ft elevation",
    harvestDate: "July 2025",
    brewing: { temperature: "80°C", time: "2-3 mins light brew" },
    tasteNotes: ["Rose", "Light", "Beauty"],
    tags: ["green tea", "rose", "beauty", "organic"],
    image: "/uploads/Green_Tea_Rose_Glow.png",
    images: ["/uploads/Green_Tea_Rose_Glow.png"]
  }
];

export { products }; 